export const CHANGE_BLOGTYPE = "page/CHANGE_BLOGTYPE"
export const CHANGE_BANNERDATA = "page/CHANGE_BANNERDATA"
export const CHANGE_AREA = "page/CHANGE_AREA"
export const CHANGE_IMGPOOL = "page/CHANGE_IMGPOOL"
export const CHANGE_BLOG = "page/BLOG"
export const CHANGE_BLOGDETAIL = "page/CHANGE_BLOGDETAIL"
